### PR TITLE
Added styling to button on hover

### LINKED ISSUE #49: Hovering over buttons in light mode doesn't look great

### PR DESCRIPTION
**Pull request by isaack-njama**
fixes #49

### CODE REVIEW

**Comment by isaack-njama** [comment]
@okjodom does this make you cringe?

**Comment by okjodom** [comment]
> @okjodom does this make you cringe?

Please add to the PR description a screenshot or video showcasing the experience changes

**Comment by isaack-njama** [comment]
Here are links to screencasts of the before and after changes:
[Before](https://drive.google.com/file/d/1IehYEh6st9hnn9vtT8AAAQ6EPhE7_-8r/view?usp=sharing)
[After](https://drive.google.com/file/d/15SpjB3DAacM_8l1qWxwTnrDMOT6-G6r7/view?usp=sharing)

**Review by naiyoma — APPROVED** [review]
this is a good improvement. let's plan to use theming in the future.

**Review by okjodom — APPROVED** [review]

**Pull request merged**
