### PR TITLE
Introduce tab system

### PR DESCRIPTION
**Pull request by okjodom**
I liked the tab system introduced by @IgboPharaoh in our chats. This PR sets up a tab system within federation card so we can build more experiences like _Deposit_ and _Withdraw_ in a compact style within the same federation card 

image

### CODE REVIEW

**Review by IgboPharaoh — COMMENTED** [review]
Good job, You can check Chakra UI to use the collapsible wrapper to render the Tabs component. 
Also, the Tablist should stretch to the end of the container like in our previous discussion  
Check [Chakra UI](https://chakra-ui.com/docs/components/tabs/usage) on how you might want to go about it

**Comment by okjodom** [comment]
> Good job, You can check Chakra UI to use the collapsible wrapper to render the Tabs component. Also, the Tablist should stretch to the end of the container like in our previous discussion Check [Chakra UI](https://chakra-ui.com/docs/components/tabs/usage) on how you might want to go about it

Let's merge and iterate on the UX polish? I don't have the bandwidth to really get it perfected, and would need your help on improving the delight of the experience

**Review by IgboPharaoh — APPROVED** [review]
Good job!, will look into other changes needed

**Comment by okjodom** [comment]
PS: now that we have the tabs system, it'd be great to showcase a placeholder deposit experience.
I'm thinking we do a demo of **Connect Fed** and the **Deposit** as the MVP of this app :)

**Pull request merged**
