### PR TITLE
Automated Lints

### PR DESCRIPTION
**Pull request by okjodom**
Configure automated lint and fix of source code with every commit

image

### CODE REVIEW

**Review by IgboPharaoh — CHANGES_REQUESTED** [review]
Great work done, but looking at the tab spaces, don't you think it might be too much?

**Comment by okjodom** [comment]
> Great work done, but looking at the tab spaces, don't you think it might be too much?

@IgboPharaoh  this proposes and automatically enforces tab size of 2 spaces. See `.prettierrc` config of tab size.
From the linting, you can then see we have deeply nested elements in our components, a sign that our components are not modular enough and we should componentize more with the benefit of flatter code

**Comment by okjodom** [comment]
Tab size or 2 spaces is pretty standard. We should keep that

**Comment by IgboPharaoh** [comment]
Alright, we'll work towards making our components more modular.
Great job

**Review by IgboPharaoh — APPROVED** [review]
Alright then, let's move forward

**Comment by okjodom** [comment]
shipping it

**Pull request merged**
